## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
np.where((array >= 3) & (array <= 8), -array, array)

**2.** Заменить максимальный элемент случайного массива на 0

In [ ]:
array[np.argmax(array)] = 0

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [3]:
result = np.array(np.meshgrid(*array)).T.reshape(-1, array.shape[0])

#i need help on this one, since i'm not sure it's the best solution

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
A[np.isin(A, B[0]).any(axis=1) & np.isin(A, B[1]).any(axis=1)]

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:
A[~((A[:, 0] == A[:, 1]) & (A[:, 1] == A[:, 2])) ]

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:
np.unique(array, axis=0)

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
#without numpy

X = np.array([
    [1, 0, 1], 
    [2, 0, 2], 
    [3, 0, 3], 
    [4, 4, 4]
    ])

result = 1

for i in range(min(len(X), len(X[0]))):
    if X[i][i] != 0:
        result *= X[i][i]

print(result)

3


In [3]:
#with numpy

X = np.array([
    [1, 0, 1], 
    [2, 0, 2], 
    [3, 0, 3], 
    [4, 4, 4]
    ])

diagonal = np.diagonal(X)
result = np.prod(diagonal[diagonal != 0])

print(result)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [13]:
#without numpy
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

result = True

if len(x) != len(y):
    result = False
else:
    for i in set(x):
        if x.count(i) != y.count(i):
            result = False

print(result)

True


In [17]:
#with numpy

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result = True

result = np.array_equal(np.sort(x), np.sort(y))

print(result)

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [21]:
#without numpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

result = None

for i in range(1, len(x)):
    if x[i - 1] == 0:
        if result is None or x[i] > result:
            result = x[i]

print(result)

5


In [4]:
#with numpy

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result = np.max(x[1:][x[:-1] == 0])
print(result)

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [10]:
#without numpy

x = [2, 2, 2, 3, 3, 3, 5]

values = [x[0]]
counts = [1]

for i in range(1, len(x)):
    if x[i] == x[i - 1]:
        counts[-1] += 1
    else:
        values.append(x[i])
        counts.append(1)

print(values, counts)

[2, 3, 5] [3, 3, 1]


In [23]:
#with numpy

x = np.array([2, 2, 2, 3, 3, 3, 5])

values = np.concatenate((
    [x[0]],
    x[1:][x[1:] != x[:-1]]
))

positions = np.concatenate((
    [0],
    np.where(x[1:] != x[:-1])[0] + 1,
    [len(x)]
))

counts = np.diff(positions)

print(values, counts)


[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
#without numpy - 2D
import math

X = [[1, 2], [3, 4], [5, 6]]
Y = [[1, 1], [4, 4]]

distances = []

for x in X:
    row = []
    for y in Y:
        distance = math.sqrt((y[0] - x[0])**2 + (y[1] - x[1])**2)
        row.append(distance)
    distances.append(row)

print(distances)

[[0.0, 4.242640687119285], [3.605551275463989, 1.0], [6.4031242374328485, 2.23606797749979]]


In [33]:
#without numpy - N-Dimensions
import math

X = [[1, 2, 3],[1, 2, 3]]
Y = [[1, 2, 3],[4, 5, 6]]

distances = []

for x in X:
    row = []
    for y in Y:
        distance = math.sqrt(
            sum(
                (a - b) ** 2
                for a, b in zip(x, y)
            )
        )
        row.append(distance)
    distances.append(row)

print(distances)

[[0.0, 5.196152422706632], [0.0, 5.196152422706632]]


In [34]:
#with numpy

X = np.array([[1, 2, 3],
              [1, 2, 3]])

Y = np.array([[1, 2, 3],
              [4, 5, 6]])

distances = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=2))

print(distances)

[[0.         5.19615242]
 [0.         5.19615242]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [4]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [41]:
average_calories = np.mean(calorie_stats)
average_calories

np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [42]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [43]:
median_calories = np.median(calorie_stats)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [5]:
np.percentile(calorie_stats, [0, 25, 50, 75, 100])

array([ 50., 100., 110., 110., 160.])

In [9]:
percentiles = np.arange(101)
values = np.percentile(calorie_stats, percentiles)
nth_percentile = np.min(percentiles[values > 60])
nth_percentile


np.int64(4)

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [10]:
more_calories = np.mean(calorie_stats > 60) * 100
more_calories

np.float64(96.1038961038961)

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [12]:
calorie_std = np.std(calorie_stats)
calorie_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
#CrunchieMunchies contains only 60 calories per serving, compared with an average of approximately 106.9 calories for competing cereals, making it significantly lower in calories. 
#The median competitor cereal contains 110 calories, and the standard deviation of about 19.35 calories shows that there is some variation, but most competitors are still considerably higher than CrunchieMunchies. 
#Only the 4th percentile is equal to or above 60 calories, while the 25th percentile already reaches 100 calories. 
#This shows that CrunchieMunchies has significantly fewer calories than most competing cereals.
#Mycrunch could use these findings to highlight CrunchieMunchies as a lower-calorie alternative in its marketing, emphasizing the substantial calorie difference compared with competing products.
